package edu.eur.absa.nlp;

import java.util.HashMap;
import java.util.HashSet;

public enum NLPTask {
	TOKENIZATION, SENTENCE_SPLITTING, POS_TAGGING, LEMMATIZATION, PARSING, DEP_PARSING, RST_PARSING, NER, 
	STANFORD_SENTIMENT_ANNOTATING,ONTOLOGY_LOOKUP, LOWERCASING, DEP_DISTANCE_ANNOTATING, CHUNKING, COREF_RESOLUTION;
	
}
